#Dockerize mysql database

#Based from mysql
FROM mysql:latest

#Root user 
ENV MYSQL_ROOT_USER root

#Root password
ENV MYSQL_ROOT_PASSWORD root

#Database used in the backend
ENV MYSQL_DATABASE school

#Expose port
EXPOSE 3306